
export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  image: string;
  brand: string;
  code: string;
  tag: string;
  partNumber?: string;
  condition?: string;
}

export const products: Product[] = [
  {
    id: "M0001",
    name: "Mitsubishi Triton 2015-22 Genuine Radiator Reserve Tank Cap 1375A433",
    description: "Genuine radiator reserve tank cap for Mitsubishi Triton models from 2015 to 2022. Ensures a perfect fit and reliable performance.",
    price: 33.00,
    image: "https://picsum.photos/seed/M0001/400/400",
    brand: "Mitsubishi Parts",
    code: "M0001",
    tag: "Mitsubishi Parts",
    partNumber: "1375A433",
    condition: "New",
  },
  {
    id: "T0001",
    name: "TOYOTA HILUX 2015-24 Genuine Left Mirror, no camera & blind spot, 5 wires BLACK",
    description: "Genuine left-side mirror for Toyota Hilux models 2015-2024. Comes in black, without camera and blind spot features, with a 5-wire connector.",
    price: 159.20,
    originalPrice: 199.00,
    image: "https://picsum.photos/seed/T0001/400/400",
    brand: "Toyota Parts",
    code: "TOYOTA HILUX 2015-24",
    tag: "Toyota Parts",
    partNumber: "87940-0K360",
    condition: "Used",
  },
  {
    id: "T0002",
    name: "TOYOTA HILUX 2015-23 GENUINE OUTER WINDOW SEALS WEATHER STRIP 4 Doors",
    description: "Complete set of genuine outer window seals for all four doors of the Toyota Hilux 2015-2023. Protects your interior from the elements.",
    price: 128.00,
    originalPrice: 160.00,
    image: "https://picsum.photos/seed/T0002/400/400",
    brand: "Toyota Parts",
    code: "TOYOTA HILUX 2015-23",
    tag: "Toyota Parts",
    partNumber: "68160-0K010",
    condition: "New",
  },
  {
    id: "T0003",
    name: "TOYOTA HILUX 2022-25 Genuine Left Mirror, blind spot, Camera not included (GLOSS BLACK)",
    description: "Genuine left-side mirror for Toyota Hilux 2022-2025 models. Gloss black finish, supports blind-spot monitoring (camera not included).",
    price: 230.40,
    originalPrice: 288.00,
    image: "https://picsum.photos/seed/T0003/400/400",
    brand: "Toyota Parts",
    code: "TOYOTA HILUX 2022-25",
    tag: "Toyota Parts",
    partNumber: "87940-0K370",
    condition: "New",
  },
  {
    id: "F0001",
    name: "Ford Ranger 2018-22 Headlight Assembly",
    description: "Complete headlight assembly for Ford Ranger models from 2018 to 2022. OEM quality for a perfect fit and optimal visibility.",
    price: 180.00,
    image: "https://picsum.photos/seed/F0001/400/400",
    brand: "Ford Parts",
    code: "FORD RANGER 18-22",
    tag: "Ford Parts",
    partNumber: "AB39-13005-AD",
    condition: "Used",
  },
  {
    id: "H0001",
    name: "Honda Civic 2020-23 Brake Pad Set",
    description: "Front brake pad set for Honda Civic models from 2020 to 2023. High-performance material for superior stopping power.",
    price: 75.50,
    image: "https://picsum.photos/seed/H0001/400/400",
    brand: "Honda Parts",
    code: "HONDA CIVIC 20-23",
    tag: "Honda Parts",
    partNumber: "45022-TBA-A00",
    condition: "New",
  },
  {
    id: "M0002",
    name: "Mazda 3 2019-22 Air Filter",
    description: "Engine air filter for Mazda 3 models from 2019 to 2022. Improves engine performance and fuel efficiency.",
    price: 25.00,
    originalPrice: 30.00,
    image: "https://picsum.photos/seed/M0002/400/400",
    brand: "Mazda Parts",
    code: "MAZDA 3 19-22",
    tag: "Mazda Parts",
    partNumber: "PE07-13-3A0A",
    condition: "New",
  },
  {
    id: "N0001",
    name: "Nissan Navara 2017-21 Tail Light Assembly",
    description: "Right-side tail light assembly for Nissan Navara models from 2017 to 2021. Durable and easy to install.",
    price: 110.00,
    image: "https://picsum.photos/seed/N0001/400/400",
    brand: "Nissan Parts",
    code: "NISSAN NAVARA 17-21",
    tag: "Nissan Parts",
    partNumber: "26550-4JA0A",
    condition: "Used",
  },
  {
    id: "S0001",
    name: "Subaru Forester 2019-23 Roof Rack Kit",
    description: "Complete roof rack kit for Subaru Forester models from 2019 to 2023. Perfect for carrying extra cargo.",
    price: 250.00,
    image: "https://picsum.photos/seed/S0001/400/400",
    brand: "Subaru Parts",
    code: "SUBARU FORESTER 19-23",
    tag: "Subaru Parts",
    partNumber: "E361SSG000",
    condition: "New",
  },
  {
    id: "V0001",
    name: "Volkswagen Golf 2018-21 Alternator",
    description: "High-output alternator for Volkswagen Golf models from 2018 to 2021. Ensures your battery stays charged and electrical systems run smoothly.",
    price: 320.00,
    originalPrice: 350.00,
    image: "https://picsum.photos/seed/V0001/400/400",
    brand: "Volkswagen Parts",
    code: "VW GOLF 18-21",
    tag: "Volkswagen Parts",
    partNumber: "06L903021J",
    condition: "Used",
  },
  {
    id: "A0001",
    name: "Audi A4 2017-2022 Genuine Oil Filter",
    description: "Genuine oil filter for Audi A4 models from 2017 to 2022. Keeps your engine oil clean and free of contaminants.",
    price: 28.50,
    image: "https://picsum.photos/seed/A0001/400/400",
    brand: "Audi Parts",
    code: "AUDI A4 17-22",
    tag: "Audi Parts",
    partNumber: "06M115561B",
    condition: "New",
  },
  {
    id: "B0001",
    name: "BMW 3 Series 2019-2023 All-Weather Floor Mats",
    description: "Custom-fit all-weather floor mats for BMW 3 Series 2019-2023. Protects your vehicle's interior from dirt, spills, and wear.",
    price: 150.00,
    originalPrice: 175.00,
    image: "https://picsum.photos/seed/B0001/400/400",
    brand: "BMW Parts",
    code: "BMW 3S 19-23",
    tag: "BMW Parts",
    partNumber: "51472458560",
    condition: "New",
  },
  {
    id: "C0001",
    name: "Chevrolet Silverado 2020-2024 Bed Liner",
    description: "Durable bed liner for Chevrolet Silverado 2020-2024. Protects your truck bed from scratches, dents, and corrosion.",
    price: 350.00,
    image: "https://picsum.photos/seed/C0001/400/400",
    brand: "Chevrolet Parts",
    code: "CHEVY SILVERADO 20-24",
    tag: "Chevrolet Parts",
    partNumber: "84347948",
    condition: "New",
  },
  {
    id: "J0001",
    name: "Jeep Wrangler 2018-2023 LED Fog Lights",
    description: "Bright LED fog lights for Jeep Wrangler 2018-2023. Improves visibility in foggy or low-light conditions.",
    price: 120.00,
    image: "https://picsum.photos/seed/J0001/400/400",
    brand: "Jeep Parts",
    code: "JEEP WRANGLER 18-23",
    tag: "Jeep Parts",
    partNumber: "82215394",
    condition: "New",
  },
  {
    id: "K0001",
    name: "Kia Sorento 2021-2024 Cargo Net",
    description: "Envelope-style cargo net for Kia Sorento 2021-2024. Keeps your cargo secure and organized.",
    price: 45.00,
    image: "https://picsum.photos/seed/K0001/400/400",
    brand: "Kia Parts",
    code: "KIA SORENTO 21-24",
    tag: "Kia Parts",
    partNumber: "U8170-1U000",
    condition: "New",
  },
  {
    id: "L0001",
    name: "Lexus RX 2020-2023 Illuminated Door Sills",
    description: "Illuminated door sills for Lexus RX 2020-2023. Adds a touch of luxury and protects your door sills from scuffs.",
    price: 280.00,
    originalPrice: 320.00,
    image: "https://picsum.photos/seed/L0001/400/400",
    brand: "Lexus Parts",
    code: "LEXUS RX 20-23",
    tag: "Lexus Parts",
    partNumber: "PT922-48200",
    condition: "New",
  },
  {
    id: "P0001",
    name: "Porsche 911 2022-2024 Indoor Car Cover",
    description: "Custom-fit indoor car cover for Porsche 911 2022-2024. Protects your vehicle from dust, dirt, and scratches.",
    price: 450.00,
    image: "https://picsum.photos/seed/P0001/400/400",
    brand: "Porsche Parts",
    code: "PORSCHE 911 22-24",
    tag: "Porsche Parts",
    partNumber: "99204400000",
    condition: "New",
  },
  {
    id: "R0001",
    name: "Ram 1500 2019-2023 Tow Hooks",
    description: "Heavy-duty tow hooks for Ram 1500 2019-2023. Provides a secure attachment point for towing or recovery.",
    price: 95.00,
    image: "https://picsum.photos/seed/R0001/400/400",
    brand: "Ram Parts",
    code: "RAM 1500 19-23",
    tag: "Ram Parts",
    partNumber: "82215298AC",
    condition: "New",
  },
  {
    id: "G0001",
    name: "GMC Sierra 2021-2024 Splash Guards",
    description: "Molded splash guards for GMC Sierra 2021-2024. Protects your vehicle's paint from mud, rocks, and other debris.",
    price: 85.00,
    image: "https://picsum.photos/seed/G0001/400/400",
    brand: "GMC Parts",
    code: "GMC SIERRA 21-24",
    tag: "GMC Parts",
    partNumber: "84347948",
    condition: "New",
  },
  {
    id: "I0001",
    name: "Isuzu D-Max 2020-2023 Bonnet Protector",
    description: "Tinted bonnet protector for Isuzu D-Max 2020-2023. Deflects insects and stones, protecting your bonnet from damage.",
    price: 110.00,
    originalPrice: 130.00,
    image: "https://picsum.photos/seed/I0001/400/400",
    brand: "Isuzu Parts",
    code: "ISUZU D-MAX 20-23",
    tag: "Isuzu Parts",
    partNumber: "UGP200001",
    condition: "New",
  }
  ,
  {
    id: "M001_NEW",
    name: "Mitsubishi Generic Part 1",
    description: "A generic part for Mitsubishi vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/M001_NEW/400/400",
    brand: "Mitsubishi Parts",
    code: "M_GENERIC_1",
    tag: "Mitsubishi Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "M002_NEW",
    name: "Mitsubishi Generic Part 2",
    description: "A generic part for Mitsubishi vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/M002_NEW/400/400",
    brand: "Mitsubishi Parts",
    code: "M_GENERIC_2",
    tag: "Mitsubishi Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "M003_NEW",
    name: "Mitsubishi Generic Part 3",
    description: "A generic part for Mitsubishi vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/M003_NEW/400/400",
    brand: "Mitsubishi Parts",
    code: "M_GENERIC_3",
    tag: "Mitsubishi Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "M004_NEW",
    name: "Mitsubishi Generic Part 4",
    description: "A generic part for Mitsubishi vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/M004_NEW/400/400",
    brand: "Mitsubishi Parts",
    code: "M_GENERIC_4",
    tag: "Mitsubishi Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "M005_NEW",
    name: "Mitsubishi Generic Part 5",
    description: "A generic part for Mitsubishi vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/M005_NEW/400/400",
    brand: "Mitsubishi Parts",
    code: "M_GENERIC_5",
    tag: "Mitsubishi Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "T001_NEW",
    name: "Toyota Generic Part 1",
    description: "A generic part for Toyota vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/T001_NEW/400/400",
    brand: "Toyota Parts",
    code: "T_GENERIC_1",
    tag: "Toyota Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "T002_NEW",
    name: "Toyota Generic Part 2",
    description: "A generic part for Toyota vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/T002_NEW/400/400",
    brand: "Toyota Parts",
    code: "T_GENERIC_2",
    tag: "Toyota Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "T003_NEW",
    name: "Toyota Generic Part 3",
    description: "A generic part for Toyota vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/T003_NEW/400/400",
    brand: "Toyota Parts",
    code: "T_GENERIC_3",
    tag: "Toyota Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "T004_NEW",
    name: "Toyota Generic Part 4",
    description: "A generic part for Toyota vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/T004_NEW/400/400",
    brand: "Toyota Parts",
    code: "T_GENERIC_4",
    tag: "Toyota Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "T005_NEW",
    name: "Toyota Generic Part 5",
    description: "A generic part for Toyota vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/T005_NEW/400/400",
    brand: "Toyota Parts",
    code: "T_GENERIC_5",
    tag: "Toyota Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "F001_NEW",
    name: "Ford Generic Part 1",
    description: "A generic part for Ford vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/F001_NEW/400/400",
    brand: "Ford Parts",
    code: "F_GENERIC_1",
    tag: "Ford Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "F002_NEW",
    name: "Ford Generic Part 2",
    description: "A generic part for Ford vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/F002_NEW/400/400",
    brand: "Ford Parts",
    code: "F_GENERIC_2",
    tag: "Ford Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "F003_NEW",
    name: "Ford Generic Part 3",
    description: "A generic part for Ford vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/F003_NEW/400/400",
    brand: "Ford Parts",
    code: "F_GENERIC_3",
    tag: "Ford Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "F004_NEW",
    name: "Ford Generic Part 4",
    description: "A generic part for Ford vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/F004_NEW/400/400",
    brand: "Ford Parts",
    code: "F_GENERIC_4",
    tag: "Ford Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "F005_NEW",
    name: "Ford Generic Part 5",
    description: "A generic part for Ford vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/F005_NEW/400/400",
    brand: "Ford Parts",
    code: "F_GENERIC_5",
    tag: "Ford Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "H001_NEW",
    name: "Honda Generic Part 1",
    description: "A generic part for Honda vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/H001_NEW/400/400",
    brand: "Honda Parts",
    code: "H_GENERIC_1",
    tag: "Honda Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "H002_NEW",
    name: "Honda Generic Part 2",
    description: "A generic part for Honda vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/H002_NEW/400/400",
    brand: "Honda Parts",
    code: "H_GENERIC_2",
    tag: "Honda Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "H003_NEW",
    name: "Honda Generic Part 3",
    description: "A generic part for Honda vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/H003_NEW/400/400",
    brand: "Honda Parts",
    code: "H_GENERIC_3",
    tag: "Honda Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "H004_NEW",
    name: "Honda Generic Part 4",
    description: "A generic part for Honda vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/H004_NEW/400/400",
    brand: "Honda Parts",
    code: "H_GENERIC_4",
    tag: "Honda Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "H005_NEW",
    name: "Honda Generic Part 5",
    description: "A generic part for Honda vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/H005_NEW/400/400",
    brand: "Honda Parts",
    code: "H_GENERIC_5",
    tag: "Honda Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "MA001_NEW",
    name: "Mazda Generic Part 1",
    description: "A generic part for Mazda vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/MA001_NEW/400/400",
    brand: "Mazda Parts",
    code: "MA_GENERIC_1",
    tag: "Mazda Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "MA002_NEW",
    name: "Mazda Generic Part 2",
    description: "A generic part for Mazda vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/MA002_NEW/400/400",
    brand: "Mazda Parts",
    code: "MA_GENERIC_2",
    tag: "Mazda Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "MA003_NEW",
    name: "Mazda Generic Part 3",
    description: "A generic part for Mazda vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/MA003_NEW/400/400",
    brand: "Mazda Parts",
    code: "MA_GENERIC_3",
    tag: "Mazda Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "MA004_NEW",
    name: "Mazda Generic Part 4",
    description: "A generic part for Mazda vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/MA004_NEW/400/400",
    brand: "Mazda Parts",
    code: "MA_GENERIC_4",
    tag: "Mazda Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "MA005_NEW",
    name: "Mazda Generic Part 5",
    description: "A generic part for Mazda vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/MA005_NEW/400/400",
    brand: "Mazda Parts",
    code: "MA_GENERIC_5",
    tag: "Mazda Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "N001_NEW",
    name: "Nissan Generic Part 1",
    description: "A generic part for Nissan vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/N001_NEW/400/400",
    brand: "Nissan Parts",
    code: "N_GENERIC_1",
    tag: "Nissan Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "N002_NEW",
    name: "Nissan Generic Part 2",
    description: "A generic part for Nissan vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/N002_NEW/400/400",
    brand: "Nissan Parts",
    code: "N_GENERIC_2",
    tag: "Nissan Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "N003_NEW",
    name: "Nissan Generic Part 3",
    description: "A generic part for Nissan vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/N003_NEW/400/400",
    brand: "Nissan Parts",
    code: "N_GENERIC_3",
    tag: "Nissan Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "N004_NEW",
    name: "Nissan Generic Part 4",
    description: "A generic part for Nissan vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/N004_NEW/400/400",
    brand: "Nissan Parts",
    code: "N_GENERIC_4",
    tag: "Nissan Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "N005_NEW",
    name: "Nissan Generic Part 5",
    description: "A generic part for Nissan vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/N005_NEW/400/400",
    brand: "Nissan Parts",
    code: "N_GENERIC_5",
    tag: "Nissan Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "S001_NEW",
    name: "Subaru Generic Part 1",
    description: "A generic part for Subaru vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/S001_NEW/400/400",
    brand: "Subaru Parts",
    code: "S_GENERIC_1",
    tag: "Subaru Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "S002_NEW",
    name: "Subaru Generic Part 2",
    description: "A generic part for Subaru vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/S002_NEW/400/400",
    brand: "Subaru Parts",
    code: "S_GENERIC_2",
    tag: "Subaru Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "S003_NEW",
    name: "Subaru Generic Part 3",
    description: "A generic part for Subaru vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/S003_NEW/400/400",
    brand: "Subaru Parts",
    code: "S_GENERIC_3",
    tag: "Subaru Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "S004_NEW",
    name: "Subaru Generic Part 4",
    description: "A generic part for Subaru vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/S004_NEW/400/400",
    brand: "Subaru Parts",
    code: "S_GENERIC_4",
    tag: "Subaru Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "S005_NEW",
    name: "Subaru Generic Part 5",
    description: "A generic part for Subaru vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/S005_NEW/400/400",
    brand: "Subaru Parts",
    code: "S_GENERIC_5",
    tag: "Subaru Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "V001_NEW",
    name: "Volkswagen Generic Part 1",
    description: "A generic part for Volkswagen vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/V001_NEW/400/400",
    brand: "Volkswagen Parts",
    code: "V_GENERIC_1",
    tag: "Volkswagen Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "V002_NEW",
    name: "Volkswagen Generic Part 2",
    description: "A generic part for Volkswagen vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/V002_NEW/400/400",
    brand: "Volkswagen Parts",
    code: "V_GENERIC_2",
    tag: "Volkswagen Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "V003_NEW",
    name: "Volkswagen Generic Part 3",
    description: "A generic part for Volkswagen vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/V003_NEW/400/400",
    brand: "Volkswagen Parts",
    code: "V_GENERIC_3",
    tag: "Volkswagen Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "V004_NEW",
    name: "Volkswagen Generic Part 4",
    description: "A generic part for Volkswagen vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/V004_NEW/400/400",
    brand: "Volkswagen Parts",
    code: "V_GENERIC_4",
    tag: "Volkswagen Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "V005_NEW",
    name: "Volkswagen Generic Part 5",
    description: "A generic part for Volkswagen vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/V005_NEW/400/400",
    brand: "Volkswagen Parts",
    code: "V_GENERIC_5",
    tag: "Volkswagen Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "A001_NEW",
    name: "Audi Generic Part 1",
    description: "A generic part for Audi vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/A001_NEW/400/400",
    brand: "Audi Parts",
    code: "A_GENERIC_1",
    tag: "Audi Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "A002_NEW",
    name: "Audi Generic Part 2",
    description: "A generic part for Audi vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/A002_NEW/400/400",
    brand: "Audi Parts",
    code: "A_GENERIC_2",
    tag: "Audi Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "A003_NEW",
    name: "Audi Generic Part 3",
    description: "A generic part for Audi vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/A003_NEW/400/400",
    brand: "Audi Parts",
    code: "A_GENERIC_3",
    tag: "Audi Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "A004_NEW",
    name: "Audi Generic Part 4",
    description: "A generic part for Audi vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/A004_NEW/400/400",
    brand: "Audi Parts",
    code: "A_GENERIC_4",
    tag: "Audi Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "A005_NEW",
    name: "Audi Generic Part 5",
    description: "A generic part for Audi vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/A005_NEW/400/400",
    brand: "Audi Parts",
    code: "A_GENERIC_5",
    tag: "Audi Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "B001_NEW",
    name: "BMW Generic Part 1",
    description: "A generic part for BMW vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/B001_NEW/400/400",
    brand: "BMW Parts",
    code: "B_GENERIC_1",
    tag: "BMW Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "B002_NEW",
    name: "BMW Generic Part 2",
    description: "A generic part for BMW vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/B002_NEW/400/400",
    brand: "BMW Parts",
    code: "B_GENERIC_2",
    tag: "BMW Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "B003_NEW",
    name: "BMW Generic Part 3",
    description: "A generic part for BMW vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/B003_NEW/400/400",
    brand: "BMW Parts",
    code: "B_GENERIC_3",
    tag: "BMW Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "B004_NEW",
    name: "BMW Generic Part 4",
    description: "A generic part for BMW vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/B004_NEW/400/400",
    brand: "BMW Parts",
    code: "B_GENERIC_4",
    tag: "BMW Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "B005_NEW",
    name: "BMW Generic Part 5",
    description: "A generic part for BMW vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/B005_NEW/400/400",
    brand: "BMW Parts",
    code: "B_GENERIC_5",
    tag: "BMW Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "C001_NEW",
    name: "Chevrolet Generic Part 1",
    description: "A generic part for Chevrolet vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/C001_NEW/400/400",
    brand: "Chevrolet Parts",
    code: "C_GENERIC_1",
    tag: "Chevrolet Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "C002_NEW",
    name: "Chevrolet Generic Part 2",
    description: "A generic part for Chevrolet vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/C002_NEW/400/400",
    brand: "Chevrolet Parts",
    code: "C_GENERIC_2",
    tag: "Chevrolet Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "C003_NEW",
    name: "Chevrolet Generic Part 3",
    description: "A generic part for Chevrolet vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/C003_NEW/400/400",
    brand: "Chevrolet Parts",
    code: "C_GENERIC_3",
    tag: "Chevrolet Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "C004_NEW",
    name: "Chevrolet Generic Part 4",
    description: "A generic part for Chevrolet vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/C004_NEW/400/400",
    brand: "Chevrolet Parts",
    code: "C_GENERIC_4",
    tag: "Chevrolet Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "C005_NEW",
    name: "Chevrolet Generic Part 5",
    description: "A generic part for Chevrolet vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/C005_NEW/400/400",
    brand: "Chevrolet Parts",
    code: "C_GENERIC_5",
    tag: "Chevrolet Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "J001_NEW",
    name: "Jeep Generic Part 1",
    description: "A generic part for Jeep vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/J001_NEW/400/400",
    brand: "Jeep Parts",
    code: "J_GENERIC_1",
    tag: "Jeep Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "J002_NEW",
    name: "Jeep Generic Part 2",
    description: "A generic part for Jeep vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/J002_NEW/400/400",
    brand: "Jeep Parts",
    code: "J_GENERIC_2",
    tag: "Jeep Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "J003_NEW",
    name: "Jeep Generic Part 3",
    description: "A generic part for Jeep vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/J003_NEW/400/400",
    brand: "Jeep Parts",
    code: "J_GENERIC_3",
    tag: "Jeep Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "J004_NEW",
    name: "Jeep Generic Part 4",
    description: "A generic part for Jeep vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/J004_NEW/400/400",
    brand: "Jeep Parts",
    code: "J_GENERIC_4",
    tag: "Jeep Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "J005_NEW",
    name: "Jeep Generic Part 5",
    description: "A generic part for Jeep vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/J005_NEW/400/400",
    brand: "Jeep Parts",
    code: "J_GENERIC_5",
    tag: "Jeep Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "K001_NEW",
    name: "Kia Generic Part 1",
    description: "A generic part for Kia vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/K001_NEW/400/400",
    brand: "Kia Parts",
    code: "K_GENERIC_1",
    tag: "Kia Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "K002_NEW",
    name: "Kia Generic Part 2",
    description: "A generic part for Kia vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/K002_NEW/400/400",
    brand: "Kia Parts",
    code: "K_GENERIC_2",
    tag: "Kia Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "K003_NEW",
    name: "Kia Generic Part 3",
    description: "A generic part for Kia vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/K003_NEW/400/400",
    brand: "Kia Parts",
    code: "K_GENERIC_3",
    tag: "Kia Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "K004_NEW",
    name: "Kia Generic Part 4",
    description: "A generic part for Kia vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/K004_NEW/400/400",
    brand: "Kia Parts",
    code: "K_GENERIC_4",
    tag: "Kia Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "K005_NEW",
    name: "Kia Generic Part 5",
    description: "A generic part for Kia vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/K005_NEW/400/400",
    brand: "Kia Parts",
    code: "K_GENERIC_5",
    tag: "Kia Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "L001_NEW",
    name: "Lexus Generic Part 1",
    description: "A generic part for Lexus vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/L001_NEW/400/400",
    brand: "Lexus Parts",
    code: "L_GENERIC_1",
    tag: "Lexus Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "L002_NEW",
    name: "Lexus Generic Part 2",
    description: "A generic part for Lexus vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/L002_NEW/400/400",
    brand: "Lexus Parts",
    code: "L_GENERIC_2",
    tag: "Lexus Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "L003_NEW",
    name: "Lexus Generic Part 3",
    description: "A generic part for Lexus vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/L003_NEW/400/400",
    brand: "Lexus Parts",
    code: "L_GENERIC_3",
    tag: "Lexus Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "L004_NEW",
    name: "Lexus Generic Part 4",
    description: "A generic part for Lexus vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/L004_NEW/400/400",
    brand: "Lexus Parts",
    code: "L_GENERIC_4",
    tag: "Lexus Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "L005_NEW",
    name: "Lexus Generic Part 5",
    description: "A generic part for Lexus vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/L005_NEW/400/400",
    brand: "Lexus Parts",
    code: "L_GENERIC_5",
    tag: "Lexus Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "P001_NEW",
    name: "Porsche Generic Part 1",
    description: "A generic part for Porsche vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/P001_NEW/400/400",
    brand: "Porsche Parts",
    code: "P_GENERIC_1",
    tag: "Porsche Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "P002_NEW",
    name: "Porsche Generic Part 2",
    description: "A generic part for Porsche vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/P002_NEW/400/400",
    brand: "Porsche Parts",
    code: "P_GENERIC_2",
    tag: "Porsche Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "P003_NEW",
    name: "Porsche Generic Part 3",
    description: "A generic part for Porsche vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/P003_NEW/400/400",
    brand: "Porsche Parts",
    code: "P_GENERIC_3",
    tag: "Porsche Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "P004_NEW",
    name: "Porsche Generic Part 4",
    description: "A generic part for Porsche vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/P004_NEW/400/400",
    brand: "Porsche Parts",
    code: "P_GENERIC_4",
    tag: "Porsche Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "P005_NEW",
    name: "Porsche Generic Part 5",
    description: "A generic part for Porsche vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/P005_NEW/400/400",
    brand: "Porsche Parts",
    code: "P_GENERIC_5",
    tag: "Porsche Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "R001_NEW",
    name: "Ram Generic Part 1",
    description: "A generic part for Ram vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/R001_NEW/400/400",
    brand: "Ram Parts",
    code: "R_GENERIC_1",
    tag: "Ram Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "R002_NEW",
    name: "Ram Generic Part 2",
    description: "A generic part for Ram vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/R002_NEW/400/400",
    brand: "Ram Parts",
    code: "R_GENERIC_2",
    tag: "Ram Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "R003_NEW",
    name: "Ram Generic Part 3",
    description: "A generic part for Ram vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/R003_NEW/400/400",
    brand: "Ram Parts",
    code: "R_GENERIC_3",
    tag: "Ram Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "R004_NEW",
    name: "Ram Generic Part 4",
    description: "A generic part for Ram vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/R004_NEW/400/400",
    brand: "Ram Parts",
    code: "R_GENERIC_4",
    tag: "Ram Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "R005_NEW",
    name: "Ram Generic Part 5",
    description: "A generic part for Ram vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/R005_NEW/400/400",
    brand: "Ram Parts",
    code: "R_GENERIC_5",
    tag: "Ram Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "G001_NEW",
    name: "GMC Generic Part 1",
    description: "A generic part for GMC vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/G001_NEW/400/400",
    brand: "GMC Parts",
    code: "G_GENERIC_1",
    tag: "GMC Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "G002_NEW",
    name: "GMC Generic Part 2",
    description: "A generic part for GMC vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/G002_NEW/400/400",
    brand: "GMC Parts",
    code: "G_GENERIC_2",
    tag: "GMC Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "G003_NEW",
    name: "GMC Generic Part 3",
    description: "A generic part for GMC vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/G003_NEW/400/400",
    brand: "GMC Parts",
    code: "G_GENERIC_3",
    tag: "GMC Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "G004_NEW",
    name: "GMC Generic Part 4",
    description: "A generic part for GMC vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/G004_NEW/400/400",
    brand: "GMC Parts",
    code: "G_GENERIC_4",
    tag: "GMC Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "G005_NEW",
    name: "GMC Generic Part 5",
    description: "A generic part for GMC vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/G005_NEW/400/400",
    brand: "GMC Parts",
    code: "G_GENERIC_5",
    tag: "GMC Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  },
  {
    id: "I001_NEW",
    name: "Isuzu Generic Part 1",
    description: "A generic part for Isuzu vehicles. This is a newly added product.",
    price: 15.00,
    image: "https://picsum.photos/seed/I001_NEW/400/400",
    brand: "Isuzu Parts",
    code: "I_GENERIC_1",
    tag: "Isuzu Parts",
    partNumber: "GENERIC_PN_1",
    condition: "New",
  },
  {
    id: "I002_NEW",
    name: "Isuzu Generic Part 2",
    description: "A generic part for Isuzu vehicles. This is a newly added product.",
    price: 20.00,
    image: "https://picsum.photos/seed/I002_NEW/400/400",
    brand: "Isuzu Parts",
    code: "I_GENERIC_2",
    tag: "Isuzu Parts",
    partNumber: "GENERIC_PN_2",
    condition: "Used",
  },
  {
    id: "I003_NEW",
    name: "Isuzu Generic Part 3",
    description: "A generic part for Isuzu vehicles. This is a newly added product.",
    price: 25.00,
    image: "https://picsum.photos/seed/I003_NEW/400/400",
    brand: "Isuzu Parts",
    code: "I_GENERIC_3",
    tag: "Isuzu Parts",
    partNumber: "GENERIC_PN_3",
    condition: "New",
  },
  {
    id: "I004_NEW",
    name: "Isuzu Generic Part 4",
    description: "A generic part for Isuzu vehicles. This is a newly added product.",
    price: 30.00,
    image: "https://picsum.photos/seed/I004_NEW/400/400",
    brand: "Isuzu Parts",
    code: "I_GENERIC_4",
    tag: "Isuzu Parts",
    partNumber: "GENERIC_PN_4",
    condition: "Used",
  },
  {
    id: "I005_NEW",
    name: "Isuzu Generic Part 5",
    description: "A generic part for Isuzu vehicles. This is a newly added product.",
    price: 35.00,
    image: "https://picsum.photos/seed/I005_NEW/400/400",
    brand: "Isuzu Parts",
    code: "I_GENERIC_5",
    tag: "Isuzu Parts",
    partNumber: "GENERIC_PN_5",
    condition: "New",
  }
];
